spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: e339674c11d1293cb058
            client-secret: 4f84d48292c5e702d50651b5ca32dbd9a1351e13

#logging:
#  level:
#    org.springframework.security: DEBUG
